### ISSUE TITLE
issue with ecdctl api v3

### ISSUE THREAD

**Issue by zposloncec** [githubixx/ansible-role-flanneld#12]
After deploying flanneld I've received error:

> Couldn't fetch network config: 100: Key not found (/kubernetes-cluster) [7] occurs.

The problem is in etcdctl api 3 version and the flannel prefix is not being created in the etcd.
My solution was to create etcd_api_version variable and use environment inside ansible:

```
environment:
    ETCDCTL_API: "{{ etcd_api_version }}"
```

for both "Check if flannel network configuration in etcd is done" and "Setup flannel network configuration in etcd if needed"

**Comment by githubixx** [comment]
I had a similar problem when I was upgrading from etcd 3.3 to 3.4 as etcd 3.4 disabled v2 API by default. I described that in my blog post: https://www.tauceti.blog/post/kubernetes-upgrade-nodes-1.16-1.17/ But besides that I didn't have any issues so far.
