### ISSUE TITLE
Unnecessary scape quotes

### ISSUE THREAD

**Issue by fjmulero** [githubixx/ansible-role-flanneld#3]
With Ansible 2.3.0 on Mac platform, I have problems with scaped single quotes:
`  shell: "{{etcd_bin_dir}}/etcdctl --ca-file={{k8s_conf_dir}}/ca-etcd.pem --cert-file={{k8s_conf_dir}}/cert-etcd.pem --key-file={{k8s_conf_dir}}/cert-etcd-key.pem set {{flannel_etcd_prefix}}/config \'{\"Network\":\"{{flannel_ip_range}}\",\"Backend\":{\"Type\": \"{{flannel_backend_type}}\"}}\'"
` 

Is not necessary scape single quotes

**Comment by githubixx** [comment]
Merged. Thanks!

**Comment by fjmulero** [comment]
Thank you for your great work
